### ISSUE TITLE
ntlk download path has no permission to write

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#110]
* Mindsdb version: last staging

I tried upload predictor, and get following error:
```
[nltk_data] Downloading package stopwords to /home/maxs/nltk_data...
ERROR:mindsdb-logger-core-logger:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:124 - Could not load module TypeDeductor

Exception on /datasources/zzz [PUT]
Traceback (most recent call last):
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/flask_restx-0.2.0-py3.6.egg/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/flask_restx-0.2.0-py3.6.egg/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/flask_restx-0.2.0-py3.6.egg/flask_restx/marshalling.py", line 248, in wrapper
    resp = f(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/api/http/namespaces/datasource.py", line 115, in put
    ca.default_store.save_datasource(ds_name, source_type, source, file_path)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/datastore/datastore.py", line 131, in save_datasource
    df_with_types = cast_df_columns_types(df, self.get_analysis(df)['data_analysis_v2'])
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/datastore/datastore.py", line 28, in get_analysis
    return self.mindsdb_native.analyse_dataset(ds)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/native/mindsdb.py", line 46, in analyse_dataset
    return F.analyse_dataset(ds)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/functional.py", line 91, in analyse_dataset
    logger=log
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 51, in __init__
    self.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 192, in run
    self._call_phase_module(module_name='TypeDeductor', input_data=self.input_data)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 121, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/type_deductor/type_deductor.py", line 303, in run
    col_name)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/type_deductor/type_deductor.py", line 244, in get_column_data_type
    nr_words, word_dist, nr_words_dist = analyze_sentences(data)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/helpers/text_helpers.py", line 64, in analyze_sentences
    nltk.download('stopwords')
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/nltk-3.5-py3.6.egg/nltk/downloader.py", line 779, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/nltk-3.5-py3.6.egg/nltk/downloader.py", line 643, in incr_download
    for msg in self._download_package(info, download_dir, force):
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/nltk-3.5-py3.6.egg/nltk/downloader.py", line 703, in _download_package
    os.mkdir(os.path.join(download_dir, info.subdir))
PermissionError: [Errno 13] Permission denied: '/home/maxs/nltk_data/corpora'
```
Probably need change ntlk path to other place.

**Comment by George3d6** [comment]
Try seeing if we can change NLTK path to the storage path of mindsdb

**Comment by George3d6** [comment]
`CONFIG.MINDSDB_STORAGE_PATH`, that is

**Comment by ZoranPandovski** [comment]
This works for me, @ilia-tsyplenkov will double check.

**Comment by ilia-tsyplenkov** [comment]
I also didn't get any errors in uploading new dataset
