### ISSUE TITLE
Using argument use_gpu=False has no effect

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#114]
I update mindsdb_native to last staging (currently same as stable 2.3.0), start train predictor with arg `use_gpu=False` and get following error:
```
ERROR:mindsdb-logger-ec5c640a-dd60-11ea-a269-2c56dc4ecd27:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:178 - CUDA error: no kernel image is available for execution on the device

Process PredictorProcess-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/native/predictor_process.py", line 33, in run
    **kwargs
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/predictor.py", line 260, in learn
    logger=self.log)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 51, in __init__
    self.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 183, in run
    self._run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 179, in _run
    raise e
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 164, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 121, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 54, in __call__
    ret = self.run(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/model_interface.py", line 31, in run
    self.transaction.model_backend.train()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/backends/lightwood.py", line 220, in train
    self.predictor.learn(from_data=train_df, test_data=test_df, callback_on_iter=self.callback_on_iter, eval_every_x_epochs=eval_every_x_epochs)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/lightwood/api/predictor.py", line 212, in learn
    from_data_ds.prepare_encoders()
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/lightwood/api/data_source.py", line 304, in prepare_encoders
    training_data=input_encoder_training_data)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/lightwood/api/data_source.py", line 267, in prepare_column_encoder
    encoder_instance.prepare_encoder(column_data)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/lightwood/encoders/text/rnn.py", line 42, in prepare_encoder
    self._encoder = EncoderRNN(self._input_lang.n_words, hidden_size).to(device)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 607, in to
    return self._apply(convert)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 161, in _apply
    self.flatten_parameters()
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 151, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
I start look what happened, came to line `mindsdb_native/mindsdb_native/libs/backends/lightwood.py#172`, lightwood.config.config.CONFIG.USE_CUDA surely equal to False.

**Comment by StpMax** [comment]
Addition info: as i realise now, this problem raise only with this dataset:
[test.zip](https://github.com/mindsdb/mindsdb_native/files/5069202/test.zip)
Other datasets train fine.

**Comment by StpMax** [comment]
Fixed by https://github.com/mindsdb/lightwood/pull/243
