### ISSUE TITLE
Error if use 'stop_training_in_x_seconds' while train predictor based on 'hdi' ds

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#291]
Last staging of all. No GPU.

I have table in database with 'hdi' dataset. If i train predictor using DS based on this table, and use 'stop_training_in_x_seconds' with small value, then i get error:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/predictor.py", line 303, in learn
    self.transaction.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 244, in run
    self._run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 240, in _run
    raise e
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 224, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 170, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/model_interface.py", line 19, in run
    self.transaction.model_backend.train()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 426, in train
    raise Exception('All models had an error while training')
Exception: All models had an error while training
```

Other it, i always get this in output:
```
ERROR:mindsdb-logger-0494df84-2357-11eb-bb81-2c56dc4ecd27:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py:396 - Traceback (most recent call last):
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 390, in train
    test_data=lightwood_test_ds
  File "/home/maxs/dev/mdb/venv_new/sources/lightwood/lightwood/api/predictor.py", line 138, in learn
    self._mixer.fit(train_ds=train_ds, test_ds=test_ds)
  File "/home/maxs/dev/mdb/venv_new/sources/lightwood/lightwood/mixers/base_mixer.py", line 51, in fit
    self._fit(train_ds, test_ds, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/lightwood/lightwood/mixers/nn.py", line 277, in _fit
    for epoch, training_error in enumerate(self._iter_fit(subset_train_ds, subset_id=subset_id)):
  File "/home/maxs/dev/mdb/venv_new/sources/lightwood/lightwood/mixers/nn.py", line 650, in _iter_fit
    target_loss = criterion(outputs[:,ds.out_indexes[k][0]:ds.out_indexes[k][1]], labels[:,ds.out_indexes[k][0]:ds.out_indexes[k][1]])
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/lightwood/lightwood/mixers/helpers/transform_corss_entropy_loss.py", line 11, in forward
    return self.cross_entropy_loss(preds, cat_labels)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 962, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/maxs/dev/mdb/venv_new/lib/python3.6/site-packages/torch/nn/functional.py", line 2264, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: weight tensor should be defined either for all 5 classes or no classes but got weight tensor of shape: [0]


ERROR:mindsdb-logger-0494df84-2357-11eb-bb81-2c56dc4ecd27:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py:397 - Exception while running NnMixer

ERROR:mindsdb-logger-0494df84-2357-11eb-bb81-2c56dc4ecd27:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:173 - Could not load module ModelInterface

ERROR:mindsdb-logger-0494df84-2357-11eb-bb81-2c56dc4ecd27:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:239 - All models had an error while training
```

To reproduce:
```
from mindsdb_native import MySqlDS, Predictor

ds2 = MySqlDS(
    database='test_data',
    host='test database host',
    port=3307,
    password='!!!password!!!',
    query='select * from test_data.hdi'
)
p = Predictor(name='hdi_test1')
p.learn(
    from_data=ds2,
    to_predict=['GDP_per_capita_USD', 'Development_Index'],
    stop_training_in_x_seconds=3     # <--- reason of errors. For 'home_rentals' work fine.
)
```

**Comment by maximlopin** [comment]
update:

- if you pass `advanced_args={'debug': True}` to `Predictor.learn` then you will see why all predictors fail to train.
- if you predict one column (instead of 2) then it doesn't raise any exceptions

**Comment by paxcema** [comment]
The underlying issue here is a bug in Lightwood when there are both categorical and non-categorical output features. See this [PR](https://github.com/mindsdb/lightwood/pull/326) for more details.

**Comment by maximlopin** [comment]
https://github.com/mindsdb/lightwood/pull/326
