### ISSUE TITLE
Failure on various benchmark datasets

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#323]
8 benchmark datasets fail to train and/or predict with mindsdb, I assume most issues are native side but I'm unsure. Here's a list of the datasets and the respective errors:

## 1. arrivals

Potentially relevant log:
```

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

INFO:mindsdb-logger-4bf08976-3029-11eb-bf0e-3f6c3b87e761---no_report:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelAnalyzer, execution time: 1.217 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 13, in run
    predictions = predictor.predict(when_data=df_test)
  File "/home/george/mindsdb_native/mindsdb_native/libs/phases/model_analyzer/model_analyzer.py", line 79, in predict_wrapper
    raise Exception('Failed to train model')
Exception: Failed to train model
Failed to train model
```

## 2.wine_quality.

Potentially relevant log:
```
INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] DataTransformer

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataTransformer, execution time: 0.011 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 0.299 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 3. hdi.

Potentially relevant log:

```

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 0.046 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 4. heart_disease

Potentially relevant log:

```
seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 0.003 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 5. insurance_claims.

Potentially relevant log:

```
INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] DataTransformer

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataTransformer, execution time: 0.005 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 0.021 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 6. eeg_eyes.

Potentially relevant log:

```

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataTransformer, execution time: 0.275 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 4.839 seconds

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 7. plantar_fasciitis.

Potentially relevant log:

```
INFO:mindsdb-logger-93038dae-303d-11eb-bf0e-3f6c3b87e761---no_report:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelAnalyzer

INFO:mindsdb-logger-93038dae-303d-11eb-bf0e-3f6c3b87e761---no_report:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelAnalyzer, execution time: 0.211 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] DataExtractor

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataExtractor, execution time: 0.006 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] DataTransformer

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataTransformer, execution time: 0.007 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 0.015 seconds

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 1810, in balanced_accuracy_score
    C = confusion_matrix(y_true, y_pred, sample_weight=sample_weight)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 281, in confusion_matrix
    labels = unique_labels(y_true, y_pred)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 103, in unique_labels
    raise ValueError("Mix of label input types (string and number)")
ValueError: Mix of label input types (string and number)
Mix of label input types (string and number)
```

## 8. occupancy_detection_ts.

Potentially relevant log:

```
INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] DataTransformer, execution time: 0.165 seconds

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:51 - [START] ModelInterface

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

INFO:mindsdb-logger-core-logger---:/home/george/mindsdb_native/mindsdb_native/libs/phases/base_module.py:56 - [END] ModelInterface, execution time: 2.170 seconds

/home/george/.local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning:

Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).

Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "/home/george/private-benchmarks/benchmarks/mdb/benchmark.py", line 16, in run
    accuracy = acc_func([x[target]['predicted_value'] for x in predictions], df_test[target])
  File "/home/george/private-benchmarks/benchmarks/datasets/occupancy_detection_ts/info.py", line 6, in rmse
    return np.sqrt(mean_squared_error(y, y_pred))
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/george/.local/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 258, in mean_squared_error
    output_errors = np.average((y_true - y_pred) ** 2, axis=0,
numpy.core._exceptions.UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')
ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')
```

**Comment by maximlopin** [comment]
https://github.com/mindsdb/private-benchmarks/pull/60

fixes `Mix of label input types (string and number)` for:
- heart_disease
- hdi
- wine_quality
- insurance_claims
- eeg_eyes
- plantar_fasciitis

**Comment by George3d6** [comment]
* arrivals
* occupancy_detection_ts

Left

**Comment by maximlopin** [comment]
fixes `A value is trying to be set on a copy of a slice from a DataFrame`: https://github.com/mindsdb/mindsdb_native/pull/324

**Comment by maximlopin** [comment]
**arrivals**
```
Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "Q:\Desktop\mdb\private-benchmarks\benchmarks\mdb\benchmark.py", line 8, in run
    predictor.learn(from_data=df_train, to_predict=target, advanced_args={'deduplicate_data': False}, **learn_kwargs)
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\predictor.py", line 296, in learn
    self.transaction.run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 244, in run
    self._run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 240, in _run
    raise e
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 224, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 170, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\model_interface.py", line 19, in run
    self.transaction.model_backend.train()
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\lightwood_backend.py", line 328, in train
    config=lightwood_config
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 103, in __init__
    self.encoders = self._prepare_encoders()
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 347, in _prepare_encoders
    encoder_instance = self._prepare_column_encoder(config, is_target=True)
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 330, in _prepare_column_encoder
    encoder_instance.prepare(column_data)
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\numeric\numeric.py", line 34, in prepare
    raise Exception(err)
Exception: Lightwood does not support working with NaN values !
Lightwood does not support working with NaN values !
```

**Comment by maximlopin** [comment]
**eeg_eyes**
```
Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "Q:\Desktop\mdb\private-benchmarks\benchmarks\mdb\benchmark.py", line 8, in run
    predictor.learn(from_data=df_train, to_predict=target, advanced_args={'deduplicate_data': False}, **learn_kwargs)
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\predictor.py", line 296, in learn
    self.transaction.run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 244, in run
    self._run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 240, in _run
    raise e
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 224, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 170, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\model_interface.py", line 19, in run
    self.transaction.model_backend.train()
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\lightwood_backend.py", line 328, in train
    config=lightwood_config
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 103, in __init__
    self.encoders = self._prepare_encoders()
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 375, in _prepare_encoders
    training_data=input_encoder_training_data)
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 327, in _prepare_column_encoder
    encoder_instance.prepare(column_data, previous_target_data=training_data['previous'])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\rnn.py", line 115, in prepare
    self._normalizer)
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\helpers\rnn_helpers.py", line 32, in tensor_from_series
    series = torch.Tensor([normalizer.encode(s) for s in series][0])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\helpers\rnn_helpers.py", line 32, in <listcomp>
    series = torch.Tensor([normalizer.encode(s) for s in series][0])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\datetime\datetime.py", line 42, in encode
    date = datetime.datetime.fromtimestamp(unix_timestamp)
ValueError: Invalid value NaN (not a number)
Invalid value NaN (not a number)
```

**Comment by maximlopin** [comment]
**occupancy_detection_ts**
```
Traceback (most recent call last):
  File "benchmarks/run.py", line 148, in main
    learn_kwargs=dataset['learn_kwargs']
  File "Q:\Desktop\mdb\private-benchmarks\benchmarks\mdb\benchmark.py", line 8, in run
    predictor.learn(from_data=df_train, to_predict=target, advanced_args={'deduplicate_data': False}, **learn_kwargs)
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\predictor.py", line 296, in learn
    self.transaction.run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 244, in run
    self._run()
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 240, in _run
    raise e
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 224, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "Q:\Desktop\mdb\mindsdb_native\mindsdb_native\libs\controllers\transaction.py", line 170, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\model_interface.py", line 19, in run
    self.transaction.model_backend.train()
  File "q:\desktop\mdb\mindsdb_native\mindsdb_native\libs\phases\model_interface\lightwood_backend.py", line 328, in train
    config=lightwood_config
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 103, in __init__
    self.encoders = self._prepare_encoders()
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 375, in _prepare_encoders
    training_data=input_encoder_training_data)
  File "Q:\Desktop\mdb\lightwood\lightwood\api\data_source.py", line 327, in _prepare_column_encoder
    encoder_instance.prepare(column_data, previous_target_data=training_data['previous'])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\rnn.py", line 115, in prepare
    self._normalizer)
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\helpers\rnn_helpers.py", line 32, in tensor_from_series
    series = torch.Tensor([normalizer.encode(s) for s in series][0])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\time_series\helpers\rnn_helpers.py", line 32, in <listcomp>
    series = torch.Tensor([normalizer.encode(s) for s in series][0])
  File "Q:\Desktop\mdb\lightwood\lightwood\encoders\datetime\datetime.py", line 42, in encode
    date = datetime.datetime.fromtimestamp(unix_timestamp)
ValueError: Invalid value NaN (not a number)
Invalid value NaN (not a number)
```

**Comment by paxcema** [comment]
* **Arrivals**: Fails to train because R2 is negative. However, predictions aren't really useless, and in this case failure should probably be determined with RMSE from within Native.
* **Occupancy detection**: uses incorrect accuracy function (sorry about that)

Will post a PR in benchmarks ASAP.

**Comment by George3d6** [comment]
All fixed in benchmark repo
