### ISSUE TITLE
Unexpected error creating a time series predictor

### ISSUE THREAD

**Issue by setohe0909** [mindsdb/mindsdb_native#354]
**Your Environment**

* Python version: 3.7
* Operating system: macOS
* Mindsdb version: 2.15.0
* MindsDB_native : 2.26.0

**Please describe your issue and how we can replicate it**
This error related to creating a time series predictor with the following data sources:
[home_rentals.csv.zip](https://github.com/mindsdb/mindsdb_native/files/5681764/home_rentals.csv.zip)

````
Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]
ERROR:mindsdb-logger-04769bca-3bf6-11eb-9a1d-60f81dc9bb8a---ae52c456-4c72-4e9f-8c8f-20af6e9626bd:/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py:181 - Could not load module ModelInterface
ERROR:mindsdb-logger-04769bca-3bf6-11eb-9a1d-60f81dc9bb8a---ae52c456-4c72-4e9f-8c8f-20af6e9626bd:/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py:269 - unsupported operand type(s) for -: 'int' and 'str'
Process PredictorProcess-1:3:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/mac/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mac/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 36, in _ts_add_previous_rows
    previous_indexes = [*range(max(0, i - window), i)]
TypeError: unsupported operand type(s) for -: 'int' and 'str'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/mac/opt/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/mac/Documents/repos/venvminds/mindsdb/mindsdb/interfaces/native/predictor_process.py", line 33, in run
    **kwargs
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/predictor.py", line 302, in learn
    self.transaction.run()
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 274, in run
    self._run()
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 270, in _run
    raise e
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 246, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 178, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/phases/model_interface/model_interface.py", line 19, in run
    self.transaction.model_backend.train()
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 297, in train
    train_df, secondary_type_dict, _ = self._ts_reshape(self.transaction.input_data.train_df)
  File "/Users/mac/Documents/repos/venvminds/lib/python3.7/site-packages/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 135, in _ts_reshape
    df_arr = pool.map(partial(_ts_add_previous_rows, historical_columns=ob_arr + self.transaction.lmd['tss']['historical_columns'], window=window), df_arr)
  File "/Users/mac/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/mac/opt/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: unsupported operand type(s) for -: 'int' and 'str'
`````

**Comment by George3d6** [comment]
The settings used were:

```
{
   "to_predict":[
      "rental_price"
   ],
   "kwargs":{
      "use_gpu":false,
      "backend":"lightwood",
      "sample_settings":{
         "sample_margin_of_error":0
      },
      "timeseries_settings":{
         "order_by":[
            "rental_price"
         ],
         "nr_predictions":1,
         "window":"20"
      }
   },
   "data_source_name":"homeRentals"
}
```

**Comment by George3d6** [comment]
```
         "order_by":[
            "rental_price"
         ]
```
Was causing it, you can't order by the same column that's being predicted.
