### ISSUE TITLE
`Could not load module DataExtractor` when DS contains JSON

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#434]
* Mindsdb version: last staging

How to reproduce:
1. run mindsdb with --api=http
2. upload url as DS: https://raw.githubusercontent.com/mindsdb/benchmarks/main/datasets/airline_delays/data.json
3. go to 'preview'

```
ERROR:mindsdb-logger-core-logger---:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py:181 - Could not load module DataExtractor

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/api/http/namespaces/datasource.py", line 165, in analyzing_thread
    analysis = default_store.get_analysis(ds['name'])
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/datastore/datastore.py", line 25, in get_analysis
    return self.mindsdb_native.analyse_dataset(self.get_datasource_obj(ds))
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/native/native.py", line 79, in analyse_dataset
    return F.analyse_dataset(ds)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/functional.py", line 101, in analyse_dataset
    tx.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 284, in run
    self._call_phase_module(module_name='DataExtractor')
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 178, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/data_extractor/data_extractor.py", line 222, in run
    result = self._get_prepared_input_df()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/data_extractor/data_extractor.py", line 124, in _get_prepared_input_df
    df = self._unnest_json_fields(df)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/data_extractor/data_extractor.py", line 59, in _unnest_json_fields
    unnested_fields = pd.json_normalize([self.transaction.lmd['unnested_fields']])
KeyError: 'unnested_fields'

ERROR:mindsdb-logger-core-logger---:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/data_sources/file_ds.py:87 - Error creating dataframe from handled data: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

ERROR:mindsdb-logger-core-logger---:/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/data_sources/file_ds.py:88 - pd.read_csv data handler would be used.
```

**Comment by maximlopin** [comment]
https://github.com/mindsdb/mindsdb_native/pull/439
