### ISSUE TITLE
Moz SQL Parser issues

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#458]
Error: 
```Traceback (most recent call last):
  File "/home/george/mindsdb_native/mindsdb_native/libs/data_types/data_source.py", line 230, in filter
    query = moz_sql_parser.format(parsed_query)
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/__init__.py", line 59, in format
    return Formatter(**kwargs).format(json)
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 153, in format
    return self.query(json)
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 291, in query
    return ' '.join(
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 294, in <genexpr>
    for part in [getattr(self, clause)(json)]
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 315, in from_
    parts.append(self.dispatch(token))
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 172, in dispatch
    return escape(json, self.ansi_quotes, self.should_quote)
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 84, in escape
    return join_field(esc(f) for f in split_field(ident))
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 60, in join_field
    output = ".".join([f.replace(".", "\\.") for f in path if f != None])
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 60, in <listcomp>
    output = ".".join([f.replace(".", "\\.") for f in path if f != None])
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 84, in <genexpr>
    return join_field(esc(f) for f in split_field(ident))
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 78, in esc
    if not should_quote(identifier):
  File "/home/george/.local/lib/python3.8/site-packages/moz_sql_parser/formatting.py", line 36, in should_quote
    not VALID.match(identifier) or identifier in RESERVED))
TypeError: argument of type 'MatchFirst' is not iterable

Failed to filter using SQL:  argument of type 'MatchFirst' is not iterable```

...

Happens inside the integration tests.

**Comment by George3d6** [comment]
I believe this was due to an invalid query, anyway, not enough info to replicate, and we might soon give up that parser in favor of Data skillet *and* the filter function is basically never used nowadays, so closing.
